const OFFER_SCREEN_IMG_COUNT = 6;
const RATING_STARS_COUNT = 5;
const ENTER_KEY = 'Enter';
const MAX_NEAR_PLACES_COUNT = 3;
const MIN_COMMENTS_LENGTH = 50;
const MAX_COMMENTS_LENGTH = 300;
const MAX_TOAST_ERRORS = 1;
const TIMOUT_ERROR_CODE = 'ECONNABORTED';
const AUTH_TOKEN_KEY_NAME = '6-cities-token';
const MAX_COMMENTS_COUNT = 10;

const RATING_TITLES = ['perfect', 'good', 'not bad', 'badly', 'terribly'];

export {
  AUTH_TOKEN_KEY_NAME,
  MAX_TOAST_ERRORS,
  TIMOUT_ERROR_CODE,
  OFFER_SCREEN_IMG_COUNT,
  RATING_STARS_COUNT,
  RATING_TITLES,
  ENTER_KEY,
  MAX_NEAR_PLACES_COUNT,
  MIN_COMMENTS_LENGTH,
  MAX_COMMENTS_LENGTH,
  MAX_COMMENTS_COUNT
};
