const OFFER_SCREEN_IMG_COUNT = 6;
const RATING_STARS_COUNT = 5;
const ENTER_KEY = 'Enter';
const MAX_NEAR_PLACES_COUNT = 3;
const MIN_COMMENTS_LENGTH = 50;
const MAX_COMMENTS_LENGTH = 300;
const ERROR = 'error';

const RATING_TITLES = ['perfect', 'good', 'not bad', 'badly', 'terribly'];

export {
  ERROR,
  OFFER_SCREEN_IMG_COUNT,
  RATING_STARS_COUNT,
  RATING_TITLES,
  ENTER_KEY,
  MAX_NEAR_PLACES_COUNT,
  MIN_COMMENTS_LENGTH,
  MAX_COMMENTS_LENGTH
};
